# This programme converts a .db file to a .csv file
# Change the "path" according to your directory

import sqlite3
import pandas as pd

# .db file directory is defined in "path" 
# .db file name is added to the "path" in "database" 

database = 'instance/test.db'
conn = sqlite3.connect(database)

# There are two data tables generated by the distributed "app.py" within database "test.db".
# The two data tables are named "page_view" and "button" (see "app.py").

query_time = "SELECT * FROM page_view"
query_button = "SELECT * FROM button"

# read_sql_query reads SQL queries into pandas DataFrames. 
# "df_table_time" and "df_table_button" are DataFrame variables.

df_table_time = pd.read_sql_query(query_time, conn)
df_table_button = pd.read_sql_query(query_button, conn)

# to_csv saves the DataFrame in a csv file. 
# After running this programme, two .csv files are generated in the same directory: "table_time.csv" and "table_button.csv".

df_table_time.to_csv('table_time.csv', index=False)
df_table_button.to_csv('table_button.csv', index=False)